### ISSUE TITLE
Add victory condition

### ISSUE THREAD

**Issue by lowkangn** [Soulcialize/souldragonknight#11]
The game should end once the Dragon and Knight reach the end of the level. For the scope of this project, there is currently only one level planned for the final release.

At the end of the level, there will be an "exit" that is only unlocked if there are no enemies left in the level.

**Comment by kenneth-fung** [comment]
The game ends when all enemies at the end of the level have been defeated; a victory screen is displayed. No exit to transfer to Level 2 is available since Level 2 does not exist in the game.
