### ISSUE TITLE
Selected role not showing when player joins a created room

### ISSUE THREAD

**Issue by lowkangn** [Soulcialize/souldragonknight#27]
If the owner of the room selects a role before the second player joins, the second player will not be able to see that that role was already selected upon joining the room.

**Comment by Eriksen2411** [comment]
But I think after he makes a choice he would know the second player role choice.

**Comment by lowkangn** [comment]
> But I think after he makes a choice he would know the second player role choice.

It actually does not, the owner has to click his selection again or another selection before the second player will be able to see. But this should quite easy to solve, just need to update the UI in the Start method I think.

**Comment by Eriksen2411** [comment]
Yeah, I see some double click needed when another player joined, but this double click I'm not sure it's because of the interaction with button or the UI did not change on the 1st click.
Yes, update in the start should be ok.
