### ISSUE TITLE
Dragon able to hit Ranged Dragon Enemy if Knight is close enough

### ISSUE THREAD

**Issue by lowkangn** [Soulcialize/souldragonknight#92]
The Dragon is able to kill Ranged Dragon Enemy if the Knight is standing close enough to the enemy, when it should be completely immune. (See the video below)

This bug is possibly caused by the raycast of the Dragon's projectile not hitting the enemy's collider before the Knight's.

https://user-images.githubusercontent.com/77261657/161076930-87498629-6bf8-4589-b5fb-c19ceb0e858c.mov

**Comment by kenneth-fung** [comment]
With the latest release, the bug has not been reproducible despite much testing. Closing for now.
